/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;

#include "stdint.h"
#include "platform_types.h"

// registers
#define RCC_BASE 0x40021000
#define PortA_BASE 0x40010800

#define RCC_APB2ENR *(volatile uint32 *)(RCC_BASE + 0x18)
#define GPIOA_CRH *(volatile uint32 *)(PortA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32 *)(PortA_BASE + 0x0C)

typedef union
{
  vuint32 all_fields; // 32bits
  struct
  {
    vuint32 reserved : 13;
    vuint32 P_13 : 1;
  } Pin;
} R_ODR_t;

volatile R_ODR_t *R_ODR = (volatile R_ODR_t *)(PortA_BASE + 0x0C);

int main(void)
{
  RCC_APB2ENR |= 1 << 2; // set bit 13
  GPIOA_CRH &= 0xFF0FFFFF;
  GPIOA_CRH |= 0x00200000;
  while (1)
  {

    // R_ODR->Pin.P_13 = 1;
    for (int i = 0; i < 5000; i++)
      ; // delay
    // R_ODR->Pin.P_13 = 0;
    GPIOA_ODR ^= (1 << 13);
    for (int i = 0; i < 5000; i++)
      ;
  }
}